# Generated by Django 4.2.3 on 2023-07-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='image_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
