# Generated by Django 4.2.3 on 2023-07-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currency_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(max_length=50)),
                ('set_up_date', models.DateField()),
                ('tenure', models.CharField(max_length=50)),
                ('initial_contract_amount', models.IntegerField(max_length=50)),
                ('rate', models.IntegerField(max_length=50)),
                ('deposits', models.IntegerField(max_length=50)),
                ('withdrawals', models.IntegerField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
