# Generated by Django 4.2.3 on 2023-07-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_portfolios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='deposits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='initial_contract_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='withdrawals',
            field=models.IntegerField(),
        ),
    ]
