# Generated by Django 4.2.3 on 2023-07-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_alter_portfolios_available_alter_portfolios_deposits_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolios',
            new_name='Portfolio',
        ),
    ]
