# Generated by Django 4.2.3 on 2023-07-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_portfolio_savepro_alter_portfolio_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='available',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='deposits',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='initial_contract_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('3', '3 Months || 3%'), ('6', '6 Months || 10%'), ('12', '12 Months || 25%')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='withdrawals',
            field=models.FloatField(),
        ),
    ]
