# Generated by Django 4.2.3 on 2023-07-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0007_alter_portfolio_available_alter_portfolio_deposits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('settled', 'Settled')], default='no', max_length=50),
        ),
    ]
