# Generated by Django 4.2.3 on 2023-07-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0008_alter_portfolio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='minwithdraw',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
