# Generated by Django 4.2.3 on 2023-07-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0009_portfolio_minwithdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='initial_contract_amount',
            new_name='investment_amount',
        ),
    ]
