# Generated by Django 4.2.3 on 2023-07-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0010_rename_initial_contract_amount_portfolio_investment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='set_up_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
