# Generated by Django 4.2.3 on 2023-07-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0011_alter_portfolio_set_up_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='set_up_date',
            new_name='setupdate',
        ),
    ]
