# Generated by Django 4.2.3 on 2023-07-28 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0013_alter_portfolio_setupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='setupdate',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 1, 13, 4, 191033)),
        ),
    ]
