# Generated by Django 4.2.3 on 2023-07-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0014_alter_portfolio_setupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='setupdate',
            field=models.DateField(),
        ),
    ]
