# Generated by Django 4.2.3 on 2023-07-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0016_alter_portfolio_available_alter_portfolio_deposits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='setupdate',
        ),
    ]
