# Generated by Django 4.2.3 on 2023-07-28 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0017_remove_portfolio_setupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='setupdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 29, 1, 45, 56, 714258), null=True),
        ),
    ]
