# Generated by Django 4.2.3 on 2023-07-28 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0018_portfolio_setupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='setupdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
