# Generated by Django 4.2.3 on 2023-07-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0020_alter_portfolio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
