# Generated by Django 4.2.3 on 2023-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0021_alter_portfolio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='setupdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
