# Generated by Django 4.2.3 on 2023-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0023_alter_portfolio_setupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
