# Generated by Django 4.2.3 on 2023-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0025_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='portfolio_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
