# Generated by Django 4.2.3 on 2023-07-30 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0026_invoice_portfolio_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(max_length=50)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'New'), ('withdraw', 'Settled')], max_length=50)),
                ('remark', models.CharField(max_length=200)),
                ('transaction_amount', models.FloatField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
