# Generated by Django 4.2.3 on 2023-07-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0028_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
