# Generated by Django 4.2.3 on 2023-07-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0031_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='invoice_id',
            new_name='wallet',
        ),
    ]
