# Generated by Django 4.2.3 on 2023-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0032_rename_invoice_id_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.CharField(max_length=50),
        ),
    ]
