# Generated by Django 4.2.3 on 2023-07-31 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0033_alter_transaction_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='portfolio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.portfolio'),
        ),
    ]
