# Generated by Django 4.2.3 on 2023-07-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0035_alter_transaction_portfolio_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='portfolio_id',
            new_name='portfolio',
        ),
    ]
