# Generated by Django 4.2.3 on 2023-08-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0036_rename_portfolio_id_transaction_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='deposits',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='withdrawals',
        ),
    ]
