# Generated by Django 4.2.3 on 2023-08-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0037_remove_portfolio_deposits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
