# Generated by Django 4.2.3 on 2023-08-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0038_alter_portfolio_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
