# Generated by Django 4.2.3 on 2023-08-11 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0039_alter_portfolio_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount_due',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
