# Generated by Django 4.2.3 on 2023-08-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0040_remove_invoice_amount_due_invoice_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='wallet',
            new_name='wallet_address',
        ),
    ]
