# Generated by Django 4.2.3 on 2023-08-27 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0042_invoice_rbf_invoice_received_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='transaction',
            name='portfolio_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
