# Generated by Django 4.2.3 on 2023-09-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0044_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0),
        ),
    ]
