# Generated by Django 4.2.3 on 2023-09-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0046_alter_message_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.CharField(max_length=50),
        ),
    ]
