# Generated by Django 4.2.3 on 2023-09-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0047_alter_message_from_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(max_length=200)),
                ('public_key', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
