# Generated by Django 4.2.3 on 2023-09-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0048_paymentaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaddress',
            name='public_key',
        ),
    ]
