# Generated by Django 4.2.3 on 2023-09-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0049_remove_paymentaddress_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaddress',
            name='invoice',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
