# Generated by Django 4.2.3 on 2023-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0050_paymentaddress_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='private_key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
